### PR TITLE
Issue #114 archived instead of index

### LINKED ISSUE #114: After tournament is deleted you should get back to Archived tournament list
Open Archived tournaments -> Delete a tournament 

- [x] #201 Redirect user after deleting tournament to the archived tournament

- [x] #202 Fix test DeletePostAction_ExistingTournament_TournamentIsDeleted

- [x] #203 Manual test if after deleting we will be redirected into archived

**AR:** You are redirected to Tournament list page
**ER:** You should be redirected to Archived tournaments page

### PR DESCRIPTION
**Pull request by BenRoman**
### Summary

Changed redirection to archived tournaments 
Fixed test DeletePostAction_ExistingTournament_TournamentIsDeleted

closes #114 

#### Design

- [ ] Web API layer contains as little logic as possible
- [ ] Domain objects use semantic names

#### Perfromance

- [ ] In case of any DB query was changed: attach generated SQL for review
- [ ] Number of DB roundtrips should be as low as possible

#### Unit Tests

- [ ] Naming: Initial state and expected result are properly stated
- [ ] Test follows [AAA](https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80) pattern.
- [ ] Test is Isolated
- [ ] Mock instances and expected instances do not share references
- [ ] When new property is added all related comparers are updated

### CODE REVIEW

**Comment by sdiachen** [comment]
Why issue in sprint backlog is not split into tasks?

**Comment by BenRoman** [comment]
I splited that issue right now  )

**Comment by sdiachen** [comment]
Manual QA task?

**Comment by BenRoman** [comment]
sorry that so late ...
but what does it mean ?

**Comment by sdiachen** [comment]
Read guide related to scrum process carefully or ask team

**Comment by BenRoman** [comment]
I tested that manually but if it is necessary i can create subtask for somebody and somebody will test that again
Did I answer in your question?

**Comment by sdiachen** [comment]
I've explicitly stated that manual test should be performed by another team member.

**Comment by BenRoman** [comment]
ok 
Sofia done that )

**Pull request merged**
